TTLocalizer: Running in language: English
OTPLocalizer: Running in language: English
Traceback (most recent call last):
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Jedi\Downloads\ToontownStride-master\toontown\toonbase\ToontownStart.py", line 184, in <module>
    from toontown.suit import Suit
  File "toontown\suit\Suit.py", line 116, in <module>
    ls = (('throw-paper', 'throw-paper', 5), ('roll-o-dex', 'roll-o-dex', 5) ('magic2', 'magic2', 5), ('phone', 'phone', 5))
TypeError: 'tuple' object is not callable
